add S2 Message Union type (#37)
* add S2 Message Union type

Signed-off-by: Victor Garcia Reolid <victor@seita.nl>

* chore: move to Literals as Pydantic 2 does

* chore: run `datamodel-codegen --input specification/openapi.yml --input-file-type openapi --output src/s2python/generated/gen_s2.py`

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: rename old S2Message to S2MessageComponent

Signed-off-by: F.N. Claessen <felix@seita.nl>

* style: pylint

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: prefer S2Message over S2MessageComponent

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Revert "refactor: prefer S2Message over S2MessageComponent"

This reverts commit fd59de63d5634dfaba55b558ad1a713baa1f39df.

* refactor: prefer S2Message over S2MessageComponent in s2_parser.py

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: `src/s2python/s2_parser.py:49: error: Dict entry 8 has incompatible type "str": "type[PPBCScheduleInstruction]"; expected "str": "Union[type[FRBCActuatorStatus], type[FRBCFillLevelTargetProfile], type[FRBCInstruction], type[FRBCLeakageBehaviour], type[FRBCStorageStatus], <13 more items>]"  [dict-item]`

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: prefer S2Message over S2MessageComponent in s2_control_type.py

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: prefer S2Message over S2MessageComponent in s2_connection.py

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: s2_parser.py has 1 place that still requires the S2MessageComponent

Signed-off-by: F.N. Claessen <felix@seita.nl>

* dev: change subject_message_id to message_id (did mypy find a bug? Related to https://github.com/flexiblepower/s2-ws-json/issues/21)

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Revert "dev: change subject_message_id to message_id (did mypy find a bug? Related to https://github.com/flexiblepower/s2-ws-json/issues/21)"

This reverts commit dc3d7064d8d9b35f48a503f5b3b903b57bdf0b40.

* fix: type ignore union-attr instead; underlying issue should be fixed under https://github.com/flexiblepower/s2-ws-json/issues/21 instead

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: linting

Signed-off-by: F.N. Claessen <felix@seita.nl>

---------

Signed-off-by: Victor Garcia Reolid <victor@seita.nl>
Signed-off-by: F.N. Claessen <felix@seita.nl>
Co-authored-by: F.N. Claessen <felix@seita.nl>